name: CI Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
env:
  OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
  OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEYID }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.NEXUS_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: chmod +x gradlew
      - run: ./gradlew clean check