name: CI Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
  OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEYID }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.NEXUS_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean test
